port: 8080

urlmapping:
  - from: "^http://hola2.com/$"
    to: "http://download.zaudera.com/public2/a.js"
  - from: "^http://hola.com/$"
    to: "http://download.zaudera.com/public/a.js"
  
filters:
  - conditions: {content_type: "javascript"}
    command: "js-beautify"
  - conditions: {content_type: "image/jpeg"}
    command: "convert"
